name: smart_cv
description: "Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: 0.11.0
  image_picker: 1.0.4
  path_provider: 2.1.2
  speech_to_text: 7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.jpg
